server {
    listen 8080;

    location /orders {
        rewrite ^/orders(/.*)?$ /api/v1/orders$1 break;
        proxy_pass http://orders-service:8081;
        include /etc/nginx/snippets/proxy-common.conf;
    }

    location /payments {
        rewrite ^/payments(/.*)?$ /api/v1/payments$1 break;
        proxy_pass http://payments-service:8082;
        include /etc/nginx/snippets/proxy-common.conf;
    }
}
